apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-deployment
spec:
    replicas: 2
    selector:
       matchLabels:
          app: my-app
    template:
       metadata:
          labels:
             app: my-app
       spec:
          containers:
          - name: test-app
            image: ralnik/test-app:v1
            ports:
              - name: web 
                containerPort: 80
            readinessProbe:
              httpGet:
                path: /
                port: 80
              periodSeconds: 2
              failureThreshold: 3
              successThreshold: 1
              timeoutSeconds: 1
            livenessProbe:
              httpGet:
                path: /
                port: 80
              periodSeconds: 10
              failureThreshold: 3
              successThreshold: 1
              timeoutSeconds: 1
              initialDelaySeconds: 10
